=== Yen13012004/XML/bin/Product_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">

	<xs:element name="Id" type="xs:positiveInteger"></xs:element>

	<xs:element name="Name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="3"></xs:minLength>
				<xs:maxLength value="50"></xs:maxLength>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Category_Id">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"></xs:minInclusive>
				<xs:maxInclusive value="9"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Desscription">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="[\s\w\n]*"></xs:pattern>
			<xs:maxLength value="128"></xs:maxLength>
		</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Amount">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"></xs:minInclusive>
				<xs:maxInclusive value="9999"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Price">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="100"></xs:minInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="Size">
     	<xs:simpleType>
     		<xs:restriction base="xs:string">
     			<xs:enumeration value="M"></xs:enumeration>
     			<xs:enumeration value="L"></xs:enumeration>
     			<xs:enumeration value="XL"></xs:enumeration>
     			<xs:enumeration value="XXL"></xs:enumeration>
     		</xs:restriction>
     	</xs:simpleType>
	</xs:element>
	
	<xs:element name="Image">
		<xs:complexType>
       	<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
       	<xs:attribute name="src" type="xs:string" use="optional"></xs:attribute>
       </xs:complexType>
	</xs:element>

	<xs:element name="Product">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Id"></xs:element>
				<xs:element ref="Name"></xs:element>
				<xs:element ref="Category_Id"></xs:element>
				<xs:element ref="Desscription"></xs:element>
				<xs:element ref="Amount"></xs:element>
				<xs:element ref="Price"></xs:element>
				<xs:element ref="Size"></xs:element>
				<xs:element ref="Image"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Products">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Product" minOccurs="0"
					maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>
		 <xs:unique name="uniqueId">
            <xs:selector xpath="Product/Id"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:unique>
	</xs:element>
</xs:schema>

=== Yen13012004/XML/bin/Product_Data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-stylesheet type="text/xsl" href="yc1.xsl"?> -->
<!-- <?xml-stylesheet type="text/xsl" href="yc2.xsl"?> -->
<?xml-stylesheet type="text/xsl" href="yc3.xsl"?>
<!-- <?xml-stylesheet type="text/xsl" href="yc4.xsl"?> -->
<!-- <?xml-stylesheet type="text/xsl" href="yc5.xsl"?> -->

<Products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Product_Schema.xsd">

	<Product>
        <Id>1</Id>
        <Name>Áo sơ mi</Name>
        <Category_Id>1</Category_Id>
        <Desscription>Sơ mi cao cấp</Desscription>
        <Amount>100</Amount>
        <Price>1000000</Price>
        <Size>M</Size>
        <Image type="jpg" src="a.jpg"/>
    </Product>
    
    <Product>
        <Id>2</Id>
        <Name>Quần bò</Name>
        <Category_Id>2</Category_Id>
        <Desscription>Quần bò rách</Desscription>
        <Amount>200</Amount>
        <Price>200000</Price>
        <Size>L</Size>
        <Image type="png" src="Anh.png"></Image>
    </Product>
    
    <Product>
        <Id>3</Id>
        <Name>Quần âu</Name>
        <Category_Id>3</Category_Id>
        <Desscription>Quần âu</Desscription>
        <Amount>1000</Amount>
        <Price>1000000</Price>
        <Size>XL</Size>
        <Image type="jpg" src="1.jpg"></Image>
    </Product>
    
    <Product>
        <Id>4</Id>
        <Name> Quần Ngố</Name>
        <Category_Id>4</Category_Id>
        <Desscription>Ngố tàu</Desscription>
        <Amount>1</Amount>
        <Price>100000000</Price>
        <Size>XXL</Size>
        <Image type="jpg" src="Pro.jpg"></Image>
    </Product>
</Products>
